baseURL: "/"
languageCode: "ru-ru"
defaultContentLanguage: "ru"
title: ITdoxy
paginate: 5
theme: PaperMod

permalinks:
  posts: /:slug/

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

languages:
  ru:
    languageName: "Русский"
    menu:
      main:
        - name: Услуги
          url: /services/
          weight: 1
        - name: Категории
          url: /categories/
          weight: 2
        - name: Архив
          url: /archives/
          weight: 3
        - name: Поиск
          url: /search/
          weight: 4

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.

  dateFormat: "02.01.2006"

  ShowReadingTime: true
  ShowShareButtons: true
  defaultTheme: auto
  disableThemeToggle: false

  # home-info mode
  homeInfoParams:
    Title: "Поваренная книга программиста"
    Content: "У нас вы сможете найти разнообразные статьи в сфере информационных технологий, посвящённые системному и сетевому администрированию, программированию, базам данных, Linux и не только."

  socialIcons:
    - name: telegram
      url: "https://t.me/ITdoxy"
    - name: vk
      url: "https://vk.com/itdoxy"
    - name: github
      url: "https://github.com/ITdoxy"
